### ISSUE TITLE
Bulk Export Plugin Not Working

### ISSUE THREAD

**Issue by AwesomeSavage** [CGJennings/strange-eons#139]
I read that the bulk export plugin was made by the creator of Strange Eons, so I am posting my issue here.

Whatever the case, when I try to use the one function the plugin adds, no matter what I use it on, after I click the "Bulk Export" button, literally nothing happens.

**Comment by AwesomeSavage** [comment]
Also, there is no related error in the plugin logs.

**Comment by CGJennings** [comment]
This should now work in both the current (3.3) and upcoming (3.4) releases. You'll need to update the plug-in via the catalogue.
