### ISSUE TITLE
How do I create new component through script?

### ISSUE THREAD

**Issue by orcun-gokbulut** [CGJennings/strange-eons#53]
Hi, I'm trying to import a generated game from different data source. In order to do that I have examined the template of the Scripted Factory. In that script 
`
    // create a new marker and fiddle with some of its properties
    var gc = new Marker();
`
I have tried to chage new Marker() statement to new AbstractGameComponent() in order to generate game card. However I received following error;
`
Uncaught JavaAdapter requires at least one argument.
	at project://New Task Name/make.js:59 (makeComponent)
	at project://New Task Name/make.js:29 (make)
	at threads:76 (task)
`

So my question is how can I create a new game component (for example an Encounter Card) from a factory script?

**Comment by CGJennings** [comment]
Closing this given the age of the issue, but feel free to ask additional questions.
