### ISSUE TITLE
Apparent Memory Leak

### ISSUE THREAD

**Issue by squk** [CGJennings/strange-eons#54]
Using `-Xmx8g -Xms2g`, when using "Make Deck" and a copies file, the deck file is constructed but the amount of allocated memory doesn't drop after constructing the deck. This is repeatable.

**Comment by CGJennings** [comment]
Thanks. Not sure that this is a complete fix, since the root cause is unknown. According to profiling, the apparently leaked objects were actually available for collection. The PR explicitly nulls those that would consume the most resources, so any remaining "leak" should at least be minor.
